language: shell
sudo: false

env:
  global:
  - secure: jkRRhM6Io/2hLQOTYsgOU6gVXdZz+DBOpDyh6g0giCVKTFl24dvaIEFKn3r+yVq260gaxM2AZNgANPdsW+J1QSo5613ljKTPcl7fL8+IAnML6VGA4WMnO9s1j8anMU3BksFn0aht+s5Qsq7+oO9WNbPur/a1ePC5Eyn64PDXqwH66BqDu+q322hHyctDfO4tVYnN5fUOSQlkVmvsES3GRFUnHXduKpXV5dYV6JYPoDddYKzr8RC8gcnINkfoETlPmA3G2oLNwjuhRZj6iLCYY0LOKtGEfk8oiNwIgGkiHVBeCPeZBrUE5miJWD41XScXkg4/isRgnzXvsIq/F22AmOZUFR4FsvgW1VyjJMUKwIXiYLSYJDcLSnFHy0XjHDS79JaQftvQ51tdDX3YcSGfyQicGdfi1mK4t55ZmJVG1GdLcBoGZ3o0QH/y9/yAFU4DI6d0qOZMkWJRnDFgNjhT8VDM4xmJ+RG3YdgbTyDapPC/kd+JmE/st1kkSvd6FybrdgyDPreFe1UkRBkdd+yY7jLzBItPECJJQOaBKOXKGoBm9TivopRtHhvLL1wyVc+kXeiRr4x4OiEGoGPNbfCmHwP7LrTTiHygnSjWyzgB5+iBwv49Zw9yk9sj+/S+WfPlZMY+08Ip4nYKJZyPo0r7IfABtpul8NDCJi88M6DzXjI=

script:
- find . -type f -name \*.sh | xargs shellcheck
- mkdir pages && cp install.sh pages/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: pages
  repo: honzahommer/acme.sh
  target_branch: gh-pages
  on:
    branch: master
