language: shell
sudo: false

env:
  global:
    secure: eCqmvUnMbQhLPvtzX218NCIRbE1FLq+wlBb8jVfEyWmbefP/V2z29uYo0OEZfuOO4ExIiUBL/UruE002vtjGZ7BnNppOd0HnAKOSUDAA/VPyH29X2lm29117TIcHpR62/75FNccpQKmj6ln3Aw6yiYgGjyGEgvMLUmR+ftY0XjK+thtsitEis0+6WOAoxFEnzWWGac8aotRSQLAVuAktYynMUtX8VRE27L0F5QwW41w425tJ1yvga/lYsb1Gc2oBJkUaAzLTD0dXnuPljxafAWKSNrd0yrf53bP5zo60uis2az2suy0SZrQMdP5ufdS3P+rEuNvhvrhTF9eYUvAORsMKrSoSWOUAE7D1nJ/ayaD9pHH+n40HWRxKH2aN6+qIQVFr+olqnHBKqB1+GbW+3h5B7LZ8dP7aJWwzzU9/4BxCVLl8QkJAprwBG261/hfCjw8cTFmlTeoFw4mrip5zusd9RNY9ifoTDzd+mk/Q1SJdSR3QP4bxWW4+1ktcnfpt7bgRfxW4NzzqeqRjU0vojFfaJa7EsuA/jL0EmkHxVdUybnh81EuXz/U3UNDEYglQJTbUK2osD19TkdJlPgPkqZRS+M95DuwEWy0cueRb7mESACeqJakzRpswBNCPCl3VQiOaZDWqYmckPhXhvpEg1yVo3/0IQMfDuMajKE+w/4k=

script:
- find . -type f -name \*.sh | xargs shellcheck
- mkdir pages && cp install.sh pages/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: pages
  repo: honzahommer/acme.sh
  target_branch: gh-pages
  on:
    branch: master
